/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 --transform --types checkered_tile_floor.glb
Files: checkered_tile_floor.glb [1.35MB] > C:\Users\mouli\r3f-webgpu\public\checkered_tile_floor-transformed.glb [78.78KB] (94%)
Author: Andrew Jepson (https://sketchfab.com/ajepson)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/checkered-tile-floor-e6c5ea5c0c8f4c9ba27f07dcb9091ffd
Title: Checkered Tile Floor
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import type { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh;
  };
  materials: {
    floor_texture: THREE.MeshStandardMaterial;
  };
};

export function Model(props: React.JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/checkered_tile_floor-transformed.glb",
  ) as unknown as GLTFResult;
  return (
    <group
      {...props}
      dispose={null}
      rotation={[Math.PI / 2, 0, 0]}
      position={[0, 0, -200]}
    >
      <mesh
        geometry={nodes.Object_2.geometry}
        material={materials.floor_texture}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/checkered_tile_floor-transformed.glb");
